version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-test:
    image: postgres:13
    container_name: postgres-test
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env.test
    volumes:
      - postgres-test:/var/lib/postgresql/data

volumes:
  postgres:
    name: hb-db

  postgres-test:
    name: hb-db-test
